server:
  port: 8085
spring:
  application:
    name: CONFIGSERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rkarama26/Microservice-Config
          clone-on-start: true






  profiles:
    active: default
